### ISSUE TITLE
[Theme Problem] Gravatar uses http instead of https

### ISSUE THREAD

**Issue by hexonMD** [saasquatch/percent-credit-theme#4]
Issue effects all 3 themes.

Ticket in desk came in that described that the gravatar url is loaded as http instead of https. 

I'm proposing we should fix this in all 3 vanilla themes in one go. 

Please let Erik know when this is done so he can inform the client that brought this up. 

Example of this issue: https://app.referralsaasquatch.com/a/test_ar164wynora0u/widgets/squatchwidget?systemId=TEST19000001&userId=gareth_test_19&email=gduplooy%40gmail.com&firstName=test19&lastName=&paramChecksum=sAxIlbXMmtPHiBlxYW6zy%2FCN506K3Mqs7smxiRDXSOY%3D&accountStatus=PAID&referralCode=ROTESSA&pageType=modalPopup&mode=POPUP&xdm_e=https%3A%2F%2Fclient.rotessa.com&xdm_c=default4765&xdm_p=1

Github url to file that uses gravatar: https://github.com/saasquatch/dollar-credit-theme/blob/master/templates/programs/CREDIT/referral.hbs

Torben:
This looks like a theme error as it looks like the GravatarHelper was designed to require passing in a "secure" option to the helper if it should use a secure URL. This option should actually be passed the value "isSecureUrl" from the theme context.

**Comment by loganvolkers** [comment]
I don't think that the commits actually fix this issue. Those changes only affect local/dev mode. cc/ @kaytcat @hexonMD @karlhorky 

I believe that this is the code snippet needed, specifically setting the `secure` option to the value of `isSecureUrl`

Before: `{{gravatar referral.email default="mm" rating="pg" size=40}}`
After: `{{gravatar referral.email default="mm" rating="pg" size=40 secure=isSecureUrl}}`

Also created this issue to better document our helpers: saasquatch/saasquatch-docs#69

**Comment by hexonMD** [comment]
Implemented Logan's fix and tested. Worked like a charm!

**Comment by karlhorky** [comment]
Ah great cheers @hexonMD @loganvolkers . Sorry, I missed the second half of the instructions here - I thought it was just to change the hardcoded urls, and worked with @kaytcat to get it implemented like that. Glad you got it fixed.
